# Generated by Django 6.0.2 on 2026-02-05 19:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kingdom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("culture_score", models.PositiveSmallIntegerField(default=10)),
                ("economy_score", models.PositiveSmallIntegerField(default=10)),
                ("loyalty_score", models.PositiveSmallIntegerField(default=10)),
                ("stability_score", models.PositiveSmallIntegerField(default=10)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("xp", models.PositiveIntegerField(default=0)),
                ("unrest", models.PositiveSmallIntegerField(default=0)),
                ("fame_points", models.PositiveSmallIntegerField(default=0)),
                (
                    "fame_type",
                    models.CharField(
                        choices=[("fame", "Fame"), ("infamy", "Infamy")],
                        default="fame",
                        max_length=6,
                    ),
                ),
                ("resource_points", models.PositiveIntegerField(default=0)),
                ("bonus_dice", models.PositiveSmallIntegerField(default=0)),
                ("penalty_dice", models.PositiveSmallIntegerField(default=0)),
                ("corruption_points", models.PositiveSmallIntegerField(default=0)),
                ("corruption_threshold", models.PositiveSmallIntegerField(default=10)),
                ("corruption_penalty", models.PositiveSmallIntegerField(default=0)),
                ("crime_points", models.PositiveSmallIntegerField(default=0)),
                ("crime_threshold", models.PositiveSmallIntegerField(default=10)),
                ("crime_penalty", models.PositiveSmallIntegerField(default=0)),
                ("strife_points", models.PositiveSmallIntegerField(default=0)),
                ("strife_threshold", models.PositiveSmallIntegerField(default=10)),
                ("strife_penalty", models.PositiveSmallIntegerField(default=0)),
                ("decay_points", models.PositiveSmallIntegerField(default=0)),
                ("decay_threshold", models.PositiveSmallIntegerField(default=10)),
                ("decay_penalty", models.PositiveSmallIntegerField(default=0)),
                ("food", models.PositiveIntegerField(default=0)),
                ("lumber", models.PositiveIntegerField(default=0)),
                ("ore", models.PositiveIntegerField(default=0)),
                ("stone", models.PositiveIntegerField(default=0)),
                ("luxuries", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KingdomMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("gm", "Game Master"), ("player", "Player")],
                        max_length=6,
                    ),
                ),
                (
                    "kingdom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kingdom_memberships",
                        to="kingdoms.kingdom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kingdom_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "kingdom")},
            },
        ),
        migrations.AddField(
            model_name="kingdom",
            name="members",
            field=models.ManyToManyField(
                related_name="kingdoms",
                through="kingdoms.KingdomMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="KingdomSkillProficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("agriculture", "Agriculture"),
                            ("arts", "Arts"),
                            ("boating", "Boating"),
                            ("defense", "Defense"),
                            ("engineering", "Engineering"),
                            ("exploration", "Exploration"),
                            ("folklore", "Folklore"),
                            ("industry", "Industry"),
                            ("intrigue", "Intrigue"),
                            ("magic", "Magic"),
                            ("politics", "Politics"),
                            ("scholarship", "Scholarship"),
                            ("statecraft", "Statecraft"),
                            ("trade", "Trade"),
                            ("warfare", "Warfare"),
                            ("wilderness", "Wilderness"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("untrained", "Untrained"),
                            ("trained", "Trained"),
                            ("expert", "Expert"),
                            ("master", "Master"),
                            ("legendary", "Legendary"),
                        ],
                        default="untrained",
                        max_length=10,
                    ),
                ),
                (
                    "kingdom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_proficiencies",
                        to="kingdoms.kingdom",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "kingdom skill proficiencies",
                "ordering": ["skill"],
                "unique_together": {("kingdom", "skill")},
            },
        ),
        migrations.CreateModel(
            name="LeadershipAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ruler", "Ruler"),
                            ("counselor", "Counselor"),
                            ("general", "General"),
                            ("emissary", "Emissary"),
                            ("magister", "Magister"),
                            ("treasurer", "Treasurer"),
                            ("viceroy", "Viceroy"),
                            ("warden", "Warden"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "character_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_pc", models.BooleanField(default=True)),
                ("is_invested", models.BooleanField(default=False)),
                ("is_vacant", models.BooleanField(default=True)),
                ("downtime_fulfilled", models.BooleanField(default=True)),
                (
                    "kingdom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadership_assignments",
                        to="kingdoms.kingdom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadership_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["role"],
                "unique_together": {("kingdom", "role")},
            },
        ),
    ]
