# Generated by Django 6.0.2 on 2026-02-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kingdoms", "0002_kingdom_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="kingdommembership",
            name="character_name",
            field=models.CharField(default="Bilbo", max_length=100),
        ),
    ]
