# Generated by Django 6.0.2 on 2026-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kingdoms", "0004_kingdomturn_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="kingdom",
            name="claimed_hexes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
