# Generated by Django 6.0.2 on 2026-02-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kingdoms", "0005_kingdom_claimed_hexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="kingdom",
            name="charter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("conquest", "Conquest"),
                    ("expansion", "Expansion"),
                    ("exploration", "Exploration"),
                    ("grant", "Grant"),
                    ("open", "Open"),
                ],
                default="",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="kingdom",
            name="government",
            field=models.CharField(
                blank=True,
                choices=[
                    ("despotism", "Despotism"),
                    ("feudalism", "Feudalism"),
                    ("oligarchy", "Oligarchy"),
                    ("republic", "Republic"),
                    ("thaumocracy", "Thaumocracy"),
                    ("yeomanry", "Yeomanry"),
                ],
                default="",
                max_length=11,
            ),
        ),
    ]
