# Generated by Django 6.0.2 on 2026-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kingdoms", "0006_kingdom_charter_kingdom_government"),
    ]

    operations = [
        migrations.AddField(
            model_name="kingdom",
            name="charter_ability_boost",
            field=models.CharField(
                blank=True,
                choices=[
                    ("culture", "Culture"),
                    ("economy", "Economy"),
                    ("loyalty", "Loyalty"),
                    ("stability", "Stability"),
                ],
                default="",
                help_text="Free ability boost granted by charter (player's choice).",
                max_length=9,
            ),
        ),
    ]
