# Generated by Django 6.0.2 on 2026-02-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kingdoms", "0007_kingdom_charter_ability_boost"),
    ]

    operations = [
        migrations.AddField(
            model_name="kingdom",
            name="government_ability_boost",
            field=models.CharField(
                blank=True,
                choices=[
                    ("culture", "Culture"),
                    ("economy", "Economy"),
                    ("loyalty", "Loyalty"),
                    ("stability", "Stability"),
                ],
                default="",
                help_text="Free ability boost granted by government (player's choice).",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="kingdom",
            name="heartland",
            field=models.CharField(
                blank=True,
                choices=[
                    ("forest_swamp", "Forest or Swamp"),
                    ("hill_plain", "Hill or Plain"),
                    ("lake_river", "Lake or River"),
                    ("mountain_ruins", "Mountain or Ruins"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
