# Generated by Django 6.0.2 on 2026-02-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kingdoms", "0008_kingdom_government_ability_boost_kingdom_heartland"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kingdomturn",
            name="in_game_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("abadius", "Abadius"),
                    ("calistril", "Calistril"),
                    ("pharast", "Pharast"),
                    ("gozran", "Gozran"),
                    ("desnus", "Desnus"),
                    ("sarenith", "Sarenith"),
                    ("erastus", "Erastus"),
                    ("arodus", "Arodus"),
                    ("rova", "Rova"),
                    ("lamashan", "Lamashan"),
                    ("neth", "Neth"),
                    ("kuthona", "Kuthona"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="kingdomturn",
            name="resource_dice_rolled",
            field=models.CharField(
                blank=True,
                choices=[
                    ("d4", "d4"),
                    ("d6", "d6"),
                    ("d8", "d8"),
                    ("d10", "d10"),
                    ("d12", "d12"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
