# Generated by Django 6.0.2 on 2026-02-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kingdoms", "0009_alter_kingdomturn_in_game_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kingdomturn",
            name="event_occurred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kingdomturn",
            name="event_xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
