# Generated by Django 6.0.2 on 2026-02-06 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kingdoms", "0010_kingdomturn_event_occurred_kingdomturn_event_xp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["turn", "-created_at"], name="kingdoms_ac_turn_id_731fbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kingdommembership",
            index=models.Index(
                fields=["kingdom", "user"], name="kingdoms_ki_kingdom_ad0ff5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kingdomturn",
            index=models.Index(
                fields=["kingdom", "-turn_number"],
                name="kingdoms_ki_kingdom_7b0289_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kingdomturn",
            index=models.Index(
                fields=["kingdom", "completed_at"],
                name="kingdoms_ki_kingdom_324188_idx",
            ),
        ),
    ]
